version: '3'
services:
  mysql:
    container_name: chatbot_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=parola
  node:
    container_name: chatbot
    build: .
    ports:
      - 80:8080
    tty: true
    links:
        - mysql
    environment:
      - MYSQL_URI=mysql://root:parola@db:3306/answers
      - PORT=8080
